#!/bin/sh
echo
echo "SimpleParser Tests"
echo "=================="
echo
php 001-block-comments.php \
    && php 002.php \
    && php 003-line-comments.php \
    && php 004-block-comments-tricky.php \
    && php 005-comments-tricky.php \
    && php 006-simple-order-by.php \
    && php 007-levels.php \
    && php 008-string-quoting-backslash.php \
    && php 009-string-quoting-double.php \
    && php 010-string-quoting-both.php \
    && php 011-tricky-parens-str-escapes.php \
    && php 012-include-subs.php \
    && php 013-dont-blank-out-comments.php \
    && php 014-preg_match_parse.php \
    && php 015-preg_replace_callback_parse.php \
    && php 016-preg_match_parse.php
